[package]
name = "rbw"
version = "1.9.0"
authors = ["Jesse Luehrs <doy@tozt.net>"]
edition = "2021"

description = "Unofficial Bitwarden CLI"
repository = "https://git.tozt.net/rbw"
readme = "README.md"
keywords = ["bitwarden"]
categories = ["command-line-utilities", "cryptography"]
license = "MIT"
include = ["src/**/*", "bin/**/*", "LICENSE", "README.md", "CHANGELOG.md"]

[dependencies]
aes = "0.8.3"
anyhow = "1.0.78"
argon2 = "0.5.2"
arrayvec = "0.7.4"
async-trait = "0.1.76"
base32 = "0.4.0"
base64 = "0.21.5"
block-padding = "0.3.3"
cbc = { version = "0.1.2", features = ["alloc", "std"] }
clap = { version = "4.4.12", features = ["wrap_help", "derive"] }
clap_complete = "4.4.5"
daemonize = "0.5.0"
# TODO: directories 5.0.1 uses MPL code, which isn't license-compatible
# we should switch to something else at some point
directories = "=5.0.0"
env_logger = "0.10.1"
futures = "0.3.30"
futures-channel = "0.3.30"
futures-util = "0.3.30"
hkdf = "0.12.4"
hmac = { version = "0.12.1", features = ["std"] }
humantime = "2.1.0"
libc = "0.2.151"
log = "0.4.20"
nix = "0.26"
pbkdf2 = "0.12.2"
percent-encoding = "2.3.1"
pkcs8 = "0.10.2"
rand = "0.8.5"
region = "3.0.0"
reqwest = { version = "0.11.23", default-features = false, features = ["blocking", "json", "rustls-tls-native-roots"] }
rsa = "0.9.6"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.109"
serde_path_to_error = "0.1.14"
serde_repr = "0.1.17"
sha1 = "0.10.6"
sha2 = "0.10.8"
tempfile = "3.9.0"
terminal_size = "0.3.0"
textwrap = "0.16.0"
thiserror = "1.0.53"
tokio = { version = "1.35.1", features = ["full"] }
tokio-stream = { version = "0.1.14", features = ["net"] }
totp-lite = "2.0.1"
url = "2.5.0"
uuid = { version = "1.6.1", features = ["v4"] }
zeroize = "1.7.0"
copypasta = "0.10.0"
rmpv = "1.0.1"
tokio-tungstenite = { version = "0.20", features = ["rustls-tls-native-roots"] }
is-terminal = "0.4.10"

[package.metadata.deb]
depends = "pinentry"
license-file = ["LICENSE"]
assets = [
    ["target/release/rbw", "usr/bin/", "755"],
    ["target/release/rbw-agent", "usr/bin/", "755"],
    ["target/release/completion/bash", "usr/share/bash-completion/completions/rbw", "644"],
    ["target/release/completion/zsh", "usr/share/zsh/vendor-completions/_rbw", "644"],
    ["target/release/completion/fish", "usr/share/fish/completions/rbw.fish", "644"],
    ["README.md", "usr/share/doc/rbw/README", "644"],
]
