[package]
name = "rbw"
version = "0.2.2"
authors = ["Jesse Luehrs <doy@tozt.net>"]
edition = "2018"

description = "Unofficial Bitwarden CLI"
repository = "https://git.tozt.net/rbw"
readme = "README.md"
keywords = ["bitwarden"]
categories = ["command-line-utilities", "cryptography"]
license = "MIT"

[dependencies]
aes = "0.3"
anyhow = "1.0"
arrayvec = "0.5"
base64 = "0.11"
block-modes = "0.3"
chbs = "0.0.10"
clap = { version = "2.33", features = ["wrap_help"] }
daemonize = "0.4"
directories = "2.0"
env_logger = "0.7"
humantime = "1.3"
log = "0.4"
nix = "0.17"
openssl = "0.10"
percent-encoding = "2.0"
rand = "0.7"
region = "2.1"
reqwest = { version = "0.10", features = ["blocking", "json"] }
ring = "0.16"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
snafu = "0.6"
tempfile = "3.1"
tokio = { version = "0.2", features = ["full"] }
uuid = { version = "0.8", features = ["v4"] }
zeroize = "1.1"

[package.metadata.deb]
depends = "pinentry"
license-file = ["LICENSE"]
